seq-cifar100:
  500:
    alpha: 0.3
    batch_size: 64
    beta: 0.5
    eta: 0.001
    lr: 0.03
    lr_milestones: [35, 45]
    lr_scheduler: multisteplr
    minibatch_size: 64
    model: xder_ce
    n_epoch: 50
    sched_multistep_lr_gamma: 0.2
